### ISSUE TITLE
Testing Riak 2.0.0 branch.

### ISSUE THREAD

**Issue by apriendeau** [nlf/riakpbc#62]
I am aware that riak2 branch is still being built but I just wanted to document what I found when writing lots (100s of gb) of data so we can research it.

```
Error: {too_many_siblings,101}
      at RiakPBC._processMessage (/var/www/vhosts/riak-backfill/releases/20140416222439/node_modules/riakpbc/index.js:40:15)
      at ConnectionManager._receive (/var/www/vhosts/riak-backfill/releases/20140416222439/node_modules/riakpbc/lib/connection-manager.js:119:10)
      at Socket.EventEmitter.emit (events.js:95:17)
      at Socket.<anonymous> (_stream_readable.js:746:14)
      at Socket.EventEmitter.emit (events.js:92:17)
      at emitReadable_ (_stream_readable.js:408:10)
      at emitReadable (_stream_readable.js:404:5)
      at readableAddChunk (_stream_readable.js:165:9)
      at Socket.Readable.push (_stream_readable.js:127:10)
      at TCP.onread (net.js:528:21)
     Failed to write
```

**Comment by oleksiyk** [comment]
This error means you are using `allow_mult=true` on your bucket and you don't resolve siblings (and/or don't use vclocks). Initially Basho planned to set `allow_mult=true` as default for 2.0 but dropped it in recent pre20 and beta1. Anyway, you should resolve your siblings (you can get siblings even with `allow_mult=false`)

**Comment by apriendeau** [comment]
We just figured that out. Literally sitting here because it was defaulting to true but we are pre20 and its default
